"use client";
import { useEffect,useState } from "react";
import { Activity,ArrowUpRight,Bookmark,BookOpen,Check,CheckCheck,ChevronRight,Compass,FileUp,Globe2,Inbox,LayoutDashboard,LogOut,Plus,RefreshCw,Settings2,ShieldCheck,X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle } from "@/components/ui/alert-dialog";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { personalizeFeed, type InterestProfile } from "@/lib/relevance";

type Story={id:string;scope:string;url:string;source_id:string;source_name:string|null;title_original:string;title_ru:string|null;title_en:string|null;fact_ru:string|null;fact_en:string|null;why_ru:string|null;why_en:string|null;action_ru:string|null;action_en:string|null;topics:string;status_label:string;state:string;demo:number;important:number;rating:string|null;saved:number;viewed_at:number|null;published_at:number;discovered_at:number;sources_json:string};
type Source={id:string;name:string;url:string;kind:string;group_name:string;enabled:number;status:string;error:string|null;last_checked:number|null;last_success:number|null};
type Week={id:string;title_ru:string;title_en:string;body_ru:string;body_en:string;story_ids:string;status:string;created_at:number};
type User={id:string;name:string;role:string;language:string;topics:string;sources:string;digest:number;bot_started:number};
type CollectionSchedule={mode:"daily"|"selected";days:number[];time_msk:string;updated_at:number};
type CollectionRun={slot:string;status:string;total:number;checked:number;added:number;errors:number;started_at:number;finished_at:number|null};
type State={authenticated:boolean;loginReady?:boolean;user?:User;stories?:Story[];interestProfile?:InterestProfile;sources?:Source[];collectionSchedule?:CollectionSchedule;collectionRun?:CollectionRun|null;suggestions?:Array<{id:string;url:string;status:string;reason:string|null;proposer?:string}>;weeks?:Week[];uploads?:Array<{id:string;filename:string;status:string;error:string|null}>;jobs?:Array<{id:string;type:string;status:string;detail:string;created_at:number}>;setup?:{openai:boolean;telegram:boolean;bot:boolean};botUsername?:string|null;error?:string};
const topics=["ИИ","Безопасность ИИ","Уязвимости","Архитектура","Разработка","Угрозы","Данные","Банковские технологии"];
const groups=["Безопасность ИИ","Реальные угрозы","Прикладная безопасность","Развитие ИИ","Независимый взгляд","Российский контекст ИБ","Предложенные"];
const ru={feed:"Лента",week:"Картина недели",saved:"Сохранённое",sources:"Источники",settings:"Настройки",admin:"Редактор",mine:"Для меня",all:"Всё",bank:"В банке",world:"В мире",both:"Оба направления",suggest:"Предложить источник",search:"Поиск по материалам",useful:"Интересно",uninteresting:"Неинтересно",save:"Сохранить",what:"Что произошло",why:"Почему это важно для УЭК",action:"На что обратить внимание",open:"Открыть первоисточник",empty:"Пока нет опубликованных материалов",emptyHint:"Материалы появятся после подключения источников и первой обработки.",demonstration:"Демонстрационный материал",important:"Важное для всех"};
const en={feed:"Feed",week:"The week",saved:"Saved",sources:"Sources",settings:"Settings",admin:"Editorial",mine:"For me",all:"All",bank:"In the bank",world:"In the world",both:"Both",suggest:"Suggest a source",search:"Search stories",useful:"Interesting",uninteresting:"Less like this",save:"Save",what:"What happened",why:"Why it matters for UEK",action:"What to check",open:"Open original",empty:"No published stories yet",emptyHint:"Stories will appear after sources are connected and processed.",demonstration:"Demo material",important:"Important for everyone"};
const parse=<T,>(s:string|undefined,f:T):T=>{try{return s?JSON.parse(s):f}catch{return f}};
const fmt=(ms:number,lang:string)=>new Date(ms).toLocaleDateString(lang==="en"?"en-US":"ru-RU",{day:"numeric",month:"short"});
function storyDate(s:Story,lang:string){
 const fromSource=Number.isFinite(s.published_at)&&Number.isFinite(s.discovered_at)&&Math.abs(s.published_at-s.discovered_at)>1000;
 const date=fromSource?s.published_at:s.discovered_at||s.published_at;
 return `${lang==="ru"?(fromSource?"Дата источника":"Добавлено"):(fromSource?"Source date":"Added")}: ${fmt(date,lang)}`;
}
function sourceHealth(s:Source,lang:string){
 const en=lang==="en";
 if(!s.enabled)return {label:en?"Paused":"Отключён",tone:"text-[#90a2ad]"};
 if(s.status==="error")return {label:en?"Check failed":"Ошибка проверки",tone:"text-[#ffaaa0]"};
 if(s.error)return {label:en?"Cannot read stories":"Не удалось прочитать",tone:"text-[#c5bfa1]"};
 if(s.status==="working")return {label:en?"Checked":"Проверен",tone:"text-[#b9f1d4]"};
 return {label:en?"Not checked yet":"Ещё не проверен",tone:"text-[#90a2ad]"};
}
function chosen(s:Story,lang:string,part:"title"|"fact"|"why"|"action"){const x=`${part}_${lang}` as keyof Story;return String(s[x]||s[`${part}_ru` as keyof Story]|| (part==="title"?s.title_original:""));}
export function RadarApp(){
 const [data,setData]=useState<State|null>(null),[screen,setScreen]=useState("feed"),[scope,setScope]=useState("all"),[mode,setMode]=useState("mine"),[query,setQuery]=useState(""),[showViewed,setShowViewed]=useState(false),[weekExpanded,setWeekExpanded]=useState(true),[markingId,setMarkingId]=useState<string|null>(null),[pendingFeedback,setPendingFeedback]=useState<Record<string,string>>({}),[feedbackErrors,setFeedbackErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[suggestUrl,setSuggestUrl]=useState(""),[suggestOpen,setSuggestOpen]=useState(false),[selected,setSelected]=useState<Story|null>(null),[draft,setDraft]=useState<Partial<Story>>({});
 const user=data?.user,lang=user?.language==="en"?"en":"ru",t=lang==="en"?en:ru;
 const reload=async()=>{try{const r=await fetch("/api/state",{cache:"no-store"});setData(await r.json());if(!r.ok)setError("Не удалось загрузить ленту")}catch{setError("Нет соединения с сайтом")}};
 const markViewed=async(s:Story)=>{
  if(s.viewed_at||markingId)return;
  setMarkingId(s.id);setError("");
  try{
   const r=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"feedback",storyId:s.id,viewed:true})});
   if(!r.ok)throw new Error("Не удалось сохранить отметку");
   setData(prev=>prev?{...prev,stories:prev.stories?.map(item=>item.id===s.id?{...item,viewed_at:Date.now()}:item)}:prev);
  }catch{setError("Не удалось отметить материал прочитанным. Попробуйте ещё раз.")}
  finally{setMarkingId(null)}
 };
 const saveFeedback=async(s:Story,kind:string,rating:string|null,saved:boolean)=>{
  if(pendingFeedback[s.id])return;
  setPendingFeedback(prev=>({...prev,[s.id]:kind}));
  setFeedbackErrors(prev=>({...prev,[s.id]:""}));
  try{
   const markRead=kind==="useful"||kind==="uninteresting";
   const response=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"feedback",storyId:s.id,rating,saved,markRead})});
   if(!response.ok){const result=await response.json() as {error?:string};throw new Error(result.error||"Не удалось сохранить выбор")}
   let refreshed:State|null=null;
   try{const result=await fetch("/api/state",{cache:"no-store"});if(result.ok)refreshed=await result.json() as State}catch{/* Local state still reflects a successful save. */}
   if(refreshed)setData(refreshed);
   else setData(prev=>prev?{...prev,stories:prev.stories?.map(item=>item.id===s.id?{...item,rating,saved:saved?1:0,viewed_at:markRead?(item.viewed_at||Date.now()):item.viewed_at}:item)}:prev);
  }catch(e){setFeedbackErrors(prev=>({...prev,[s.id]:e instanceof Error?e.message:"Не удалось сохранить выбор. Попробуйте ещё раз."}))}
  finally{setPendingFeedback(prev=>{const next={...prev};delete next[s.id];return next})}
 };
 useEffect(()=>{let active=true;void fetch("/api/state",{cache:"no-store"}).then(r=>r.json()).then(v=>{if(!active)return;const state=v as State;setData(state);const target=new URLSearchParams(window.location.search).get("story");const matched=state.stories?.find(s=>s.id===target);if(matched){setSelected(matched);setDraft(matched)}}).catch(()=>{if(active)setError("Нет соединения с сайтом")});return()=>{active=false}},[]);
 const act=async(action:string,payload:Record<string,unknown>={})=>{setBusy(action);setError("");setNotice("");try{const r=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const result=await r.json() as {error?:string;outcomes?:Array<{source:string}>};if(!r.ok)throw new Error(result.error||"Ошибка");await reload();setNotice(action.startsWith("collect")?"Проверен источник: "+(result.outcomes||[]).map((x:{source:string})=>x.source).join(", "):"Сохранено");return result}catch(e){setError(e instanceof Error?e.message:"Ошибка запроса");return null}finally{setBusy("")}};
 useEffect(()=>{
  if(!data?.authenticated)return;
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(value:unknown)=>Promise<unknown>};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  const submit=async(payload:Record<string,unknown>)=>{
   const response=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
   const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Не удалось сохранить");
   const updated=await fetch("/api/state",{cache:"no-store"});if(updated.ok)setData(await updated.json() as State);
   return {ok:true};
  };
  const tools:Tool[]=[
   {name:"propose_source",title:"Предложить источник",description:"Предложить публичный HTTPS канал или сайт для постоянного мониторинга. Заявка уйдёт редактору на проверку.",inputSchema:{type:"object",properties:{url:{type:"string",format:"uri"}},required:["url"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{const url=(input as {url?:unknown})?.url;if(typeof url!=="string"||!url.startsWith("https://"))throw new Error("Нужна ссылка https://");return submit({action:"suggest",url})}},
   {name:"save_story",title:"Сохранить материал",description:"Сохранить опубликованную карточку в разделе «Сохранённое» по её идентификатору.",inputSchema:{type:"object",properties:{storyId:{type:"string"}},required:["storyId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{const storyId=(input as {storyId?:unknown})?.storyId;if(typeof storyId!=="string"||!storyId)throw new Error("Нужен идентификатор карточки");return submit({action:"feedback",storyId,saved:true})}}
  ];
  for(const tool of tools)void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});
  return()=>controller.abort();
 },[data?.authenticated,data?.user?.id]);
 const preferences=parse<string[]>(user?.topics,[]),preferredSources=parse<string[]>(user?.sources,[]);
 const items=(()=>{
  const entries=(data?.stories||[]).filter(s=>scope==="all"||s.scope===scope).filter(s=>screen!=="saved"||s.saved).filter(s=>!query||`${s.title_ru} ${s.title_en} ${s.fact_ru} ${s.fact_en}`.toLowerCase().includes(query.toLowerCase()));
  if(mode==="all"||screen==="saved"||query.trim())return entries;
  return personalizeFeed(entries,data?.interestProfile||{topics:{},sources:{},positives:0,negatives:0},preferences,preferredSources);
 })();
 const unreadItems=items.filter(s=>!s.viewed_at),viewedItems=items.filter(s=>Boolean(s.viewed_at));
 const storyCount=data?.stories?.length||0,latest=(data?.weeks||[]).find(w=>w.status==="published");
 if(!data)return <div className="grid min-h-screen place-items-center text-[#b9f1d4]"><RefreshCw className="animate-spin"/></div>;
 if(!data.authenticated)return <main className="min-h-screen grid place-items-center px-5"><div className="max-w-lg w-full rounded-[28px] border border-[#344655] bg-[#14202d] p-8 sm:p-12"><div className="flex items-center gap-3 text-[#b9f1d4]"><Activity size={28}/><span className="text-sm tracking-[.2em] uppercase">УЭК / Радар</span></div><h1 className="mt-12 text-[clamp(2.1rem,5vw,3.4rem)] leading-[1.1] font-semibold">Контекст, который помогает видеть дальше.</h1><p className="mt-5 text-[#a9b9c0] text-base leading-7">Безопасность, ИИ и события внутри банка — с коротким разбором для работы эксперта.</p>{data.loginReady?<a href="/auth/start" className="mt-10 inline-flex h-12 items-center rounded-xl bg-[#b9f1d4] px-6 text-[#0d1420] font-semibold">Войти через Telegram <ChevronRight className="ml-3 size-4"/></a>:<p className="mt-10 rounded-xl border border-[#7a5b49] bg-[#2e2826] px-5 py-4 text-[#f0c8ab]">Вход через Telegram ещё настраивается. Для запуска нужен бот и параметры входа от BotFather.</p>}</div></main>;
 const renderStory=(s:Story)=><StoryCard key={s.id} story={s} lang={lang} t={t} onOpen={()=>{setSelected(s);setDraft(s)}} onMarkRead={()=>{void markViewed(s)}} markingRead={markingId===s.id} pendingFeedback={pendingFeedback[s.id]} feedbackError={feedbackErrors[s.id]} onFeedback={(kind,rating,saved)=>{void saveFeedback(s,kind,rating,saved)}}/>;
 const nav=[{id:"feed",icon:LayoutDashboard,label:t.feed},{id:"week",icon:Compass,label:t.week},{id:"saved",icon:Bookmark,label:t.saved},{id:"sources",icon:BookOpen,label:t.sources},{id:"settings",icon:Settings2,label:t.settings},...(user?.role==="admin"?[{id:"admin",icon:ShieldCheck,label:t.admin}]:[])];
 return <div className="min-h-screen min-w-0 bg-[#0d1420] text-[#ecf3f4]">
  <div className="mx-auto max-w-[1550px] lg:grid lg:grid-cols-[236px_minmax(0,1fr)]">
   <aside className="lg:sticky lg:top-0 lg:h-screen border-b lg:border-r border-[#344655] bg-[#101b28] px-4 py-5 sm:px-8 lg:px-7 lg:py-8 flex flex-col gap-5">
    <div className="flex items-center gap-3 lg:mb-11 shrink-0"><div className="grid size-10 place-items-center rounded-xl border border-[#b9f1d4]/50 text-[#b9f1d4]"><Activity size={22}/></div><div><div className="text-[11px] uppercase tracking-[.2em] text-[#90a2ad]">Эксперт УЭК</div><div className="font-semibold text-[19px] leading-5">Радар</div></div></div>
    <nav className="grid grid-cols-3 min-w-0 gap-2 lg:flex lg:flex-col lg:gap-1" aria-label="Разделы">{nav.map(n=><button key={n.id} onClick={()=>setScreen(n.id)} className={`flex min-w-0 min-h-[72px] flex-col items-center justify-center gap-1 rounded-xl px-1.5 py-2 text-center text-sm leading-tight transition-colors lg:min-h-11 lg:w-full lg:flex-row lg:justify-start lg:gap-3 lg:px-3.5 lg:text-left lg:text-[15px] ${screen===n.id?"bg-[#254338] text-[#c8f7dc]":"text-[#a9b9c0] hover:bg-[#1d2e3c] hover:text-white"}`}><n.icon size={18} className="shrink-0"/><span className="min-w-0 break-words">{n.label}</span></button>)}</nav>
    <div className="hidden lg:block mt-auto pt-4 border-t border-[#344655]"><p className="text-sm font-medium truncate">{user?.name}</p><p className="mt-1 text-xs text-[#90a2ad]">{user?.role==="admin"?"Администратор / редактор":"Читатель"}</p><a href="/auth/logout" className="mt-4 inline-flex items-center gap-2 text-sm text-[#a9b9c0] hover:text-white"><LogOut size={15}/>Выйти</a></div>
   </aside>
   <div className="min-w-0">
    <header className="sticky top-0 z-10 border-b border-[#344655] bg-[#0d1420]/95 backdrop-blur-xl px-5 sm:px-8 lg:px-11 py-4 flex items-center gap-4 justify-between"><div className="text-sm text-[#a9b9c0] hidden sm:block">{screen==="feed"?"Главное для эксперта":nav.find(n=>n.id===screen)?.label}</div><div className="ml-auto flex items-center gap-3"><span className="hidden sm:inline text-xs text-[#95acb5]">{storyCount} материалов</span><span className="text-xs rounded-full border border-[#344655] px-3 py-1.5">{lang.toUpperCase()}</span><div className="size-9 rounded-full bg-[#294a3c] grid place-items-center font-semibold text-[#b9f1d4]">{user?.name?.[0]?.toUpperCase()||"У"}</div></div></header>
    <div className="min-w-0 px-4 sm:px-8 lg:px-11 py-8 lg:py-11 max-w-[1180px]">
    {error&&<div role="alert" className="mb-6 rounded-xl border border-[#a66a62] bg-[#442e32] px-5 py-3 text-sm">{error}<button onClick={()=>setError("")} className="float-right" aria-label="Закрыть"><X size={15}/></button></div>}
    {notice&&<div role="status" className="mb-6 rounded-xl border border-[#4d8567] bg-[#254338] px-5 py-3 text-sm">{notice}</div>}
    {(screen==="feed"||screen==="saved")&&<>
      <div className="flex items-start justify-between gap-5"><div><p className="text-xs uppercase tracking-[.2em] text-[#b9f1d4]">{new Date().toLocaleDateString(lang==="en"?"en-US":"ru-RU",{weekday:"long",day:"numeric",month:"long"})}</p><h1 className="mt-3 text-[clamp(2.2rem,4vw,3.8rem)] font-semibold leading-tight tracking-tight">{screen==="saved"?t.saved:lang==="ru"?"В поле зрения":"In focus"}</h1><p className="mt-2 text-[#a9b9c0] max-w-[560px]">{lang==="ru"?"События и идеи, которые могут изменить нашу работу.":"Events and ideas that may change how we work."}</p></div><Dialog open={suggestOpen} onOpenChange={setSuggestOpen}><DialogTrigger asChild><Button className="hidden sm:inline-flex rounded-xl mt-2"><Plus size={16}/>{t.suggest}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{t.suggest}</DialogTitle></DialogHeader><p className="text-sm text-[#a9b9c0]">{lang==="ru"?"Ссылка на канал или площадку для постоянного наблюдения":"Link to a channel or website to monitor"}</p><Input placeholder="https://..." value={suggestUrl} onChange={e=>setSuggestUrl(e.target.value)}/><Button disabled={busy==="suggest"} onClick={async()=>{if(await act("suggest",{url:suggestUrl})){setSuggestOpen(false);setSuggestUrl("")}}}>{lang==="ru"?"Отправить":"Submit"}</Button></DialogContent></Dialog></div>
      {screen==="feed"&&latest&&<WeeklyFeature week={latest} lang={lang} expanded={weekExpanded} onToggle={()=>setWeekExpanded(x=>!x)} onOpen={()=>setScreen("week")} stories={data.stories||[]}/>}<div className="mt-9 flex min-w-0 flex-col md:flex-row md:items-center justify-between gap-4 border-y border-[#344655] py-4"><div className="flex min-w-0 flex-col sm:flex-row sm:flex-wrap sm:items-center gap-3 sm:gap-4"><Tabs value={mode} onValueChange={setMode} className="w-full sm:w-auto"><TabsList className="grid w-full grid-cols-2 min-h-12 group-data-[orientation=horizontal]/tabs:h-auto bg-[#1d2e3c] sm:inline-flex sm:w-fit sm:min-h-0 sm:group-data-[orientation=horizontal]/tabs:h-9"><TabsTrigger value="mine" className="min-w-0">{t.mine}</TabsTrigger><TabsTrigger value="all" className="min-w-0">{t.all}</TabsTrigger></TabsList></Tabs><Tabs value={scope} onValueChange={setScope} className="w-full sm:w-auto"><TabsList className="grid w-full grid-cols-3 min-h-12 group-data-[orientation=horizontal]/tabs:h-auto bg-[#1d2e3c] sm:inline-flex sm:w-fit sm:min-h-0 sm:group-data-[orientation=horizontal]/tabs:h-9"><TabsTrigger value="all" className="min-w-0 whitespace-normal text-center leading-tight">{t.both}</TabsTrigger><TabsTrigger value="bank" className="min-w-0 whitespace-normal text-center leading-tight">{t.bank}</TabsTrigger><TabsTrigger value="world" className="min-w-0 whitespace-normal text-center leading-tight">{t.world}</TabsTrigger></TabsList></Tabs></div><div className="relative max-w-xs w-full"><Globe2 className="absolute left-3 top-2.5 size-4 text-[#90a2ad]"/><Input aria-label={t.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="pl-9 bg-[#14202d] border-[#344655]"/></div></div>
      <div className="mt-8 grid min-w-0 grid-cols-[minmax(0,1fr)] xl:grid-cols-[minmax(0,1fr)_290px] gap-7"><div className="min-w-0 space-y-4">{items.length?<>
        {(screen==="feed"?unreadItems:items).map(renderStory)}
        {screen==="feed"&&viewedItems.length>0&&<section className="pt-4" aria-label={lang==="ru"?"Просмотренные материалы":"Viewed stories"}>
         <button type="button" onClick={()=>setShowViewed(v=>!v)} aria-expanded={showViewed} aria-controls="viewed-stories" className="flex min-h-14 w-full items-center justify-between gap-4 rounded-xl border border-[#344655] bg-[#14202d] px-4 py-3 text-left text-sm font-medium text-[#b9f1d4] hover:border-[#568475] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#b9f1d4]">
          <span>{lang==="ru"?"Просмотрено":"Viewed"} <span className="ml-1 text-[#a9b9c0]">{viewedItems.length}</span></span>
          <span className="inline-flex shrink-0 items-center gap-1">{lang==="ru"?(showViewed?"Свернуть":"Показать"):(showViewed?"Collapse":"Show")}<ChevronRight size={17} className={`transition-transform ${showViewed?"rotate-90":""}`}/></span>
         </button>
         <div id="viewed-stories" className={showViewed?"mt-4 space-y-4":"hidden"}>{showViewed&&viewedItems.map(renderStory)}</div>
        </section>}
       </>:<div className="border border-[#344655] rounded-2xl bg-[#14202d] p-9 min-h-[230px]"><Inbox className="text-[#b9f1d4]" size={29}/><h2 className="mt-5 text-xl font-semibold">{t.empty}</h2><p className="mt-2 text-[#a9b9c0]">{mode==="mine"&&storyCount?lang==="ru"?"Попробуйте изменить интересы или переключиться на «Всё».":"Adjust your interests or choose All.":t.emptyHint}</p></div>}</div><div className="space-y-5"><div className="rounded-2xl border border-[#344655] bg-[#14202d] p-6"><p className="text-xs uppercase tracking-[.16em] text-[#90a2ad]">{lang==="ru"?"Твой контекст":"Your context"}</p><div className="mt-4 flex flex-wrap gap-2">{preferences.length?preferences.map(x=><span key={x} className="rounded-full bg-[#244438] text-[#c8f7dc] px-3 py-1.5 text-xs">{x}</span>):<span className="text-sm text-[#a9b9c0]">{lang==="ru"?"Темы пока не выбраны":"No topics selected"}</span>}</div><button onClick={()=>setScreen("settings")} className="mt-5 text-sm text-[#b9f1d4]">{lang==="ru"?"Настроить ленту →":"Tune your feed →"}</button></div></div></div>
     </>}
     {screen==="week"&&<section><Eyebrow>Обзор</Eyebrow><h1 className="page-title">{t.week}</h1>{(data.weeks||[]).length?(data.weeks||[]).map(w=><div key={w.id} className="panel mt-5"><div className="flex justify-between"><span className="text-sm text-[#b9f1d4]">{fmt(w.created_at,lang)}</span>{w.status==="draft"&&<span className="text-xs">Черновик</span>}</div><h2 className="text-2xl font-semibold mt-4">{lang==="ru"?w.title_ru:w.title_en}</h2><div className="mt-5"><WeeklyBody body={lang==="ru"?w.body_ru:w.body_en}/></div><div className="mt-6 pt-4 border-t border-[#344655] text-sm text-[#90a2ad]">{lang==="ru"?"Материалы обзора":"Sources"}: {parse<string[]>(w.story_ids,[]).map(id=>data.stories?.find(s=>s.id===id)).filter(Boolean).map(s=><button key={s!.id} onClick={()=>{setSelected(s!);setDraft(s!)}} className="block mt-2 text-left text-[#b9f1d4] hover:underline">{chosen(s!,lang,"title")}</button>)}</div></div>):<Empty>Первый обзор появится после накопления материалов за неделю.</Empty>}</section>}
     {screen==="sources"&&<section><Eyebrow>Наблюдаем</Eyebrow><h1 className="page-title">{t.sources}</h1><p className="mt-3 text-[#a9b9c0]">{lang==="ru"?"Площадки в списке мониторинга. Можно предложить свою.":"Sources in the monitoring list. You can suggest another."}</p><div className="mt-6 flex flex-wrap gap-2"><Button onClick={()=>setSuggestOpen(true)}><Plus size={16}/>{t.suggest}</Button>{user?.role==="admin"&&<Button variant="secondary" onClick={()=>setScreen("admin")}>Управлять источниками</Button>}</div><Dialog open={suggestOpen} onOpenChange={setSuggestOpen}><DialogContent><DialogHeader><DialogTitle>{t.suggest}</DialogTitle></DialogHeader><p className="text-sm text-[#a9b9c0]">Ссылка на канал или площадку для постоянного наблюдения</p><Input placeholder="https://..." value={suggestUrl} onChange={e=>setSuggestUrl(e.target.value)}/><Button onClick={async()=>{if(await act("suggest",{url:suggestUrl})){setSuggestOpen(false);setSuggestUrl("")}}}>Отправить</Button></DialogContent></Dialog>{groups.map(g=>{const ss=(data.sources||[]).filter(s=>s.group_name===g);return ss.length?<div key={g} className="mt-9"><h2 className="text-lg font-semibold mb-3">{g}</h2><div className="space-y-2">{ss.map(s=>{const health=sourceHealth(s,lang);return <div key={s.id} className="panel !p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 sm:gap-3"><div className="min-w-0"><a className="text-[#eaf4f2] hover:text-[#b9f1d4] font-medium" href={s.url} target="_blank" rel="noopener noreferrer">{s.name} ↗</a><p className="mt-1 text-xs text-[#90a2ad] truncate">{s.url}</p></div><span className={`text-xs self-start sm:self-auto shrink-0 ${health.tone}`}>{health.label}</span></div>})}</div></div>:null})}<h2 className="mt-11 text-lg font-semibold">{lang==="ru"?"Мои предложения":"My suggestions"}</h2>{(data.suggestions||[]).map(s=><div className="panel !p-4 mt-2" key={s.id}><span className="text-sm break-all">{s.url}</span><span className="ml-3 text-xs text-[#b9f1d4]">{s.status}</span>{s.reason&&<p className="text-sm mt-1 text-[#a9b9c0]">{s.reason}</p>}</div>)}</section>}
     {screen==="settings"&&<Settings user={user!} sources={data.sources||[]} lang={lang} busy={busy} onSave={v=>act("settings",v)} botUsername={data.botUsername}/>}
     {screen==="admin"&&user?.role==="admin"&&<AdminPanel data={data} busy={busy} act={act} reload={reload} onEdit={s=>{setSelected(s);setDraft(s)}}/>}
    </div>
   </div>
  </div>
  <Dialog open={Boolean(selected)} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="max-h-[88vh] min-w-0 overflow-y-auto [overflow-wrap:anywhere] sm:max-w-[760px] bg-[#14202d] border-[#45606b]">{selected&&<div><p className="text-xs uppercase tracking-widest text-[#b9f1d4]">{selected.scope==="bank"?t.bank:t.world} · {selected.source_name||"УЭК"} · {storyDate(selected,lang)}</p><h2 className="mt-4 pr-7 text-2xl font-semibold leading-tight">{chosen(selected,lang,"title")}</h2>{selected.demo===1&&<p className="mt-2 text-xs text-[#e0c095]">{t.demonstration}</p>}{(["fact","why","action"] as const).map((part,i)=><div key={part} className="mt-6"><div className="text-xs uppercase tracking-widest text-[#90a2ad]">{[t.what,t.why,t.action][i]}</div><p className="mt-2 text-[16px] leading-7 text-[#e4f0ef]">{chosen(selected,lang,part)||"—"}</p></div>)}<div className="mt-7 border-t border-[#344655] pt-5 space-y-2">{parse<Array<{name:string;url:string|null}>>(selected.sources_json,[]).map((source,i)=>source.url?<a key={i} href={source.url} target="_blank" rel="noopener noreferrer" className="block text-sm text-[#b9f1d4] hover:underline">{source.name} ↗</a>:<p key={i} className="text-sm text-[#a9b9c0]">{source.name}</p>)}</div>{user?.role==="admin"&&<div className="mt-7 rounded-xl bg-[#1d2e3c] p-4 space-y-3"><h3 className="font-semibold">Редактировать карточку</h3>{(["title_ru","title_en","fact_ru","fact_en","why_ru","why_en","action_ru","action_en"] as const).map(k=><label key={k} className="block text-xs text-[#90a2ad]">{k}<textarea className="mt-1 block min-h-14 w-full rounded-lg border border-[#45606b] bg-[#14202d] px-3 py-2 text-sm text-white" value={String(draft[k]||"")} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>{void act("story",{id:selected.id,titleRu:draft.title_ru,titleEn:draft.title_en,factRu:draft.fact_ru,factEn:draft.fact_en,whyRu:draft.why_ru,whyEn:draft.why_en,actionRu:draft.action_ru,actionEn:draft.action_en,topics:parse(draft.topics,[]),statusLabel:draft.status_label,important:Boolean(draft.important),state:"published"});setSelected(null)}}>Сохранить и опубликовать</Button><Button variant="secondary" size="sm" onClick={()=>{void act("story",{id:selected.id,...{titleRu:draft.title_ru,titleEn:draft.title_en,factRu:draft.fact_ru,factEn:draft.fact_en,whyRu:draft.why_ru,whyEn:draft.why_en,actionRu:draft.action_ru,actionEn:draft.action_en,topics:parse(draft.topics,[]),statusLabel:draft.status_label,important:Boolean(draft.important),state:"hidden"}});setSelected(null)}}>Скрыть</Button></div></div>}</div>}</DialogContent></Dialog>
 </div>;
}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="text-xs uppercase tracking-[.2em] text-[#b9f1d4]">{children}</p>}
function Empty({children}:{children:React.ReactNode}){return <div className="panel mt-8 text-[#a9b9c0]">{children}</div>}
function WeeklyBody({body}:{body:string}){
 const blocks=body.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);
 return <div className="space-y-4 text-[16px] leading-7 text-[#d3e2dd]">{blocks.map((block,i)=>{
  const lines=block.split("\n");
  if(lines[0].startsWith("## "))return <div key={i} className="pt-2"><h3 className="text-base font-semibold text-[#eaf4f2]">{lines[0].slice(3)}</h3>{lines.length>1&&(lines.slice(1).every(x=>x.startsWith("- "))?<ul className="mt-2 list-disc space-y-1 pl-5">{lines.slice(1).map((x,j)=><li key={j}>{x.slice(2)}</li>)}</ul>:<p className="mt-2">{lines.slice(1).join(" ")}</p>)}</div>;
  if(block.startsWith("Для УЭК:")||block.startsWith("For UEK:"))return <p key={i} className="border-l-2 border-[#80b69a] pl-4 text-[#bdd8c8]">{block}</p>;
  if(lines.every(x=>x.startsWith("- ")))return <ul key={i} className="list-disc space-y-1 pl-5">{lines.map((x,j)=><li key={j}>{x.slice(2)}</li>)}</ul>;
  return <p key={i}>{block}</p>;
 })}</div>;
}
function WeeklyFeature({week,lang,expanded,onToggle,onOpen,stories}:{week:Week;lang:string;expanded:boolean;onToggle:()=>void;onOpen:()=>void;stories:Story[]}){
 const ids=parse<string[]>(week.story_ids,[]),linked=ids.map(id=>stories.find(s=>s.id===id)).filter((s):s is Story=>Boolean(s));
 return <section className="mt-8 min-w-0 max-w-full rounded-2xl border border-[#456956] bg-[#193329] p-5 sm:p-7 [overflow-wrap:anywhere]" aria-label={lang==="ru"?"Картина недели":"The week"}>
  <div className="flex flex-wrap items-center justify-between gap-3"><span className="text-xs uppercase tracking-[.16em] text-[#b9f1d4]">{lang==="ru"?"Картина недели":"The week"} · {fmt(week.created_at,lang)}</span><button type="button" className="inline-flex items-center gap-1 text-sm text-[#b9f1d4]" aria-expanded={expanded} onClick={onToggle}>{lang==="ru"?(expanded?"Свернуть":"Развернуть"):(expanded?"Collapse":"Expand")}<ChevronRight size={17} className={`transition-transform ${expanded?"rotate-90":""}`}/></button></div>
  <h2 className="mt-3 text-xl sm:text-2xl font-semibold leading-tight">{lang==="ru"?week.title_ru:week.title_en}</h2>
  {expanded&&<><div className="mt-5"><WeeklyBody body={lang==="ru"?week.body_ru:week.body_en}/></div>{linked.length>0&&<div className="mt-6 border-t border-[#456956] pt-4"><p className="text-xs uppercase tracking-wider text-[#a3c8b4]">{lang==="ru"?`Материалы обзора · ${linked.length}`:`Sources · ${linked.length}`}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2">{linked.map(s=><a key={s.id} href={s.url} target="_blank" rel="noopener noreferrer" className="max-w-full text-sm text-[#b9f1d4] hover:underline">{chosen(s,lang,"title")} ↗</a>)}</div><p className="mt-3 text-xs text-[#a3bcae]">{lang==="ru"?"В выпуске — материалы с датой публикации за последние 7 дней.":"This edition uses stories dated within the last 7 days."}</p></div>}<button type="button" onClick={onOpen} className="mt-5 text-sm text-[#b9f1d4] hover:underline">{lang==="ru"?"Все выпуски":"All editions"} →</button></>}
 </section>;
}
function StoryCard({story:s,lang,t,onOpen,onMarkRead,markingRead,pendingFeedback,feedbackError,onFeedback}:{story:Story;lang:string;t:typeof ru;onOpen:()=>void;onMarkRead:()=>void;markingRead:boolean;pendingFeedback?:string;feedbackError?:string;onFeedback:(kind:string,r:string|null,saved:boolean)=>void}){
 const labels=parse<string[]>(s.topics,[]);
 const original=s.scope==="world"&&/^https?:\/\//.test(s.url)?s.url:null;
 const actionClass="min-h-11 min-w-0 w-full sm:w-auto rounded-xl border border-[#607789] bg-[#223443] px-3 text-[#e5eff0] whitespace-normal text-center leading-tight hover:border-[#8db39f] hover:bg-[#2b4553] focus-visible:ring-[#b9f1d4]/60 sm:whitespace-nowrap";
 const selectedClass="border-[#87cba3] bg-[#244b3d] text-[#d6f8e3] hover:bg-[#2d5b49]";
 const mutedClass="border-[#c39b86] bg-[#4b3a35] text-[#f0d0bb] hover:bg-[#59443d]";
 const actionsBusy=Boolean(pendingFeedback)||markingRead;
 return <article className="min-w-0 max-w-full rounded-2xl border border-[#344655] bg-[#14202d] p-4 sm:p-7 [overflow-wrap:anywhere] hover:border-[#568475] transition-colors">
  <div className="flex min-w-0 gap-x-2 gap-y-1 items-center text-xs text-[#a9b9c0] flex-wrap">
   <span className="uppercase tracking-widest text-[#b9f1d4]">{s.scope==="bank"?t.bank:t.world}</span><span>·</span><span>{s.source_name||"УЭК"}</span><span>·</span><span>{storyDate(s,lang)}</span>
   {s.important===1&&<span className="text-[#e9ca8f]">★ {t.important}</span>}
   {Boolean(s.viewed_at)&&<span className="text-[#90a2ad]">· {lang==="ru"?"Просмотрено":"Viewed"}</span>}
  </div>
  <button onClick={onOpen} className="block max-w-full mt-4 text-left"><h2 className="text-[21px] sm:text-[25px] leading-[1.3] font-semibold hover:text-[#b9f1d4]">{chosen(s,lang,"title")}</h2></button>
  <p className="mt-4 text-[#d3dfdf] leading-7">{chosen(s,lang,"fact")}</p>
  {chosen(s,lang,"why")&&<p className="mt-4 pl-4 border-l-2 border-[#b9f1d4] text-[#bcd5c9] text-sm leading-6">{chosen(s,lang,"why")}</p>}
  <div className="mt-5 flex flex-wrap gap-2">{labels.map(topic=><span key={topic} className="text-xs rounded-full border border-[#3a5657] px-3 py-1 text-[#a7c4bf]">{topic}</span>)}{s.demo===1&&<span className="text-xs rounded-full border border-[#9a7953] px-3 py-1 text-[#e0c095]">{t.demonstration}</span>}</div>
  <div className="mt-6 grid grid-cols-2 gap-2 border-t border-[#344655] pt-4 sm:flex sm:flex-wrap sm:items-center">
   <Button type="button" variant="secondary" size="sm" className={`${actionClass} ${s.rating==="useful"?selectedClass:""}`} disabled={actionsBusy} aria-pressed={s.rating==="useful"} onClick={()=>onFeedback("useful",s.rating==="useful"?null:"useful",Boolean(s.saved))}>{pendingFeedback==="useful"?<RefreshCw size={15} className="animate-spin"/>:<Check size={15}/>}<span>{pendingFeedback==="useful"?(lang==="ru"?"Сохраняем…":"Saving…"):t.useful}</span></Button>
   <Button type="button" variant="secondary" size="sm" className={`${actionClass} ${s.rating==="uninteresting"?mutedClass:""}`} disabled={actionsBusy} aria-pressed={s.rating==="uninteresting"} onClick={()=>onFeedback("uninteresting",s.rating==="uninteresting"?null:"uninteresting",Boolean(s.saved))}>{pendingFeedback==="uninteresting"?<RefreshCw size={15} className="animate-spin"/>:<X size={15}/>}<span>{pendingFeedback==="uninteresting"?(lang==="ru"?"Сохраняем…":"Saving…"):t.uninteresting}</span></Button>
   <Button type="button" variant="secondary" size="sm" className={`${actionClass} ${s.saved?selectedClass:""}`} disabled={actionsBusy} aria-pressed={Boolean(s.saved)} onClick={()=>onFeedback("saved",s.rating,!s.saved)}>{pendingFeedback==="saved"?<RefreshCw size={15} className="animate-spin"/>:<Bookmark size={15}/>}<span>{pendingFeedback==="saved"?(lang==="ru"?"Сохраняем…":"Saving…"):t.save}</span></Button>
   {!s.viewed_at&&<Button type="button" variant="secondary" size="sm" className={actionClass} disabled={actionsBusy} onClick={onMarkRead}>{markingRead?<RefreshCw size={15} className="animate-spin"/>:<CheckCheck size={15}/>}<span>{markingRead?(lang==="ru"?"Сохраняем…":"Saving…"):(lang==="ru"?"Прочитано":"Mark read")}</span></Button>}
   {original?<Button asChild variant="secondary" size="sm" className={`${actionClass} col-span-2 sm:ml-auto`}><a href={original} target="_blank" rel="noopener noreferrer" aria-label={`${lang==="ru"?"Открыть публикацию":"Open original"}: ${chosen(s,lang,"title")}`}>{lang==="ru"?"Подробнее":"Read more"}<ArrowUpRight size={15}/></a></Button>:<Button type="button" variant="secondary" size="sm" className={`${actionClass} col-span-2 sm:ml-auto`} onClick={onOpen}>{lang==="ru"?"Разбор":"Analysis"}<ChevronRight size={15}/></Button>}
  </div>
  {feedbackError&&<p role="alert" className="mt-3 text-sm text-[#ffaaa0]">{feedbackError}</p>}
 </article>;
}
function Settings({user,sources,lang,busy,onSave,botUsername}:{user:User;sources:Source[];lang:string;busy:string;onSave:(v:Record<string,unknown>)=>void;botUsername?:string|null}){
 const [language,setLanguage]=useState(user.language),[myTopics,setTopics]=useState(parse<string[]>(user.topics,[])),[mySources,setSources]=useState(parse<string[]>(user.sources,[])),[digest,setDigest]=useState(Boolean(user.digest));
 const toggle=(xs:string[],v:string)=>xs.includes(v)?xs.filter(x=>x!==v):[...xs,v];
 return <section><Eyebrow>Персонализация</Eyebrow><h1 className="page-title">{lang==="ru"?"Настроить радар":"Tune your radar"}</h1><div className="mt-8 grid lg:grid-cols-2 gap-5"><div className="panel"><h2 className="text-xl font-semibold">{lang==="ru"?"Интересующие темы":"Topics"}</h2><p className="hint">{lang==="ru"?"Оценки «Интересно» и «Неинтересно» помогают ленте учиться. Важное для всех останется видимым.":"Interesting and Less like this help tune your feed. Important stories remain visible."}</p><div className="mt-5 grid gap-3">{topics.map(topic=><label key={topic} className="flex items-center gap-3 text-sm"><Checkbox checked={myTopics.includes(topic)} onCheckedChange={()=>setTopics(toggle(myTopics,topic))}/>{topic}</label>)}</div></div><div className="panel"><h2 className="text-xl font-semibold">{lang==="ru"?"Источники":"Sources"}</h2><p className="hint">{lang==="ru"?"Выбранные площадки поднимутся в «Для меня».":"Selected sources are prioritised in For me."}</p><div className="mt-5 grid gap-3 max-h-80 overflow-y-auto">{sources.map(source=><label key={source.id} className="flex items-center gap-3 text-sm"><Checkbox checked={mySources.includes(source.id)} onCheckedChange={()=>setSources(toggle(mySources,source.id))}/>{source.name}</label>)}</div></div><div className="panel"><h2 className="text-xl font-semibold">{lang==="ru"?"Язык":"Language"}</h2><div className="mt-5 flex gap-2"><Button onClick={()=>setLanguage("ru")} variant={language==="ru"?"default":"secondary"}>Русский</Button><Button onClick={()=>setLanguage("en")} variant={language==="en"?"default":"secondary"}>English</Button></div></div><div className="panel"><h2 className="text-xl font-semibold">{lang==="ru"?"Недельная подборка":"Weekly digest"}</h2><p className="hint">{lang==="ru"?"Персональный выпуск приходит в Telegram на выбранном языке.":"A personalised Telegram digest in your chosen language."}</p><label className="mt-5 flex items-center gap-3 text-sm"><Switch checked={digest} onCheckedChange={setDigest}/>{lang==="ru"?"Получать раз в неделю":"Send weekly"}</label>{!user.bot_started&&<p className="mt-4 text-sm text-[#e4c995]">{lang==="ru"?"Чтобы бот мог отправить выпуск, откройте его и нажмите Start. После этого обновите страницу.":"Open the bot and press Start to enable delivery."}{botUsername?<a className="block mt-3 text-[#b9f1d4] underline" href={`https://t.me/${botUsername}`} target="_blank" rel="noopener noreferrer">Открыть бота ↗</a>:" Бот пока не настроен."}</p>}{Boolean(user.bot_started)&&<p className="mt-4 text-sm text-[#b9f1d4]">✓ Telegram подключён</p>}</div></div><Button className="mt-7" disabled={busy==="settings"} onClick={()=>onSave({language,topics:myTopics,sources:mySources,digest})}>{lang==="ru"?"Сохранить настройки":"Save settings"}</Button></section>;
}
type SourceDraft={id:string;name:string;url:string;kind:string;group:string};
const emptySource:SourceDraft={id:"",name:"",url:"",kind:"web",group:"Развитие ИИ"};
function SourceManager({sources,busy,act,reload}:{sources:Source[];busy:string;act:(name:string,payload?:Record<string,unknown>)=>Promise<unknown>;reload:()=>Promise<void>}){
 const [draft,setDraft]=useState<SourceDraft>(emptySource),[open,setOpen]=useState(false),[removing,setRemoving]=useState<Source|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const manage=async(action:string,payload:Record<string,unknown>)=>{
  setSaving(true);setError("");
  try{
   const response=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});
   const result=await response.json() as {error?:string};
   if(!response.ok)throw new Error(result.error||"Не удалось сохранить источник");
   await reload();return true;
  }catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить источник");return false}
  finally{setSaving(false)}
 };
 const startCreate=()=>{setDraft(emptySource);setError("");setOpen(true)};
 const startEdit=(source:Source)=>{setDraft({id:source.id,name:source.name,url:source.url,kind:source.kind,group:source.group_name});setError("");setOpen(true)};
 const save=async()=>{if(await manage(draft.id?"sourceUpdate":"sourceCreate",draft)){setOpen(false);setDraft(emptySource)}};
 return <div className="panel min-w-0">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Внешние источники</h2><p className="hint">Добавляйте площадки, меняйте настройки и проверяйте сбор.</p></div><Button onClick={startCreate} disabled={saving||Boolean(busy)}><Plus size={16}/>Добавить источник</Button></div>
  <Button className="mt-5" variant="secondary" disabled={saving||Boolean(busy)} onClick={()=>{void act("collect")}}><RefreshCw size={16}/>{busy==="collect"?"Проверяем…":"Проверить следующий"}</Button>
  {error&&<p className="mt-4 text-sm text-[#ffaaa0]" role="alert">{error}</p>}
  <div className="mt-5 max-h-[32rem] overflow-y-auto space-y-0.5">{sources.map(source=><div key={source.id} className="border-t border-[#344655] py-3 min-w-0"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><a href={source.url} target="_blank" rel="noopener noreferrer" className="font-medium text-[#eaf4f2] hover:text-[#b9f1d4]">{source.name} ↗</a><p className="mt-1 text-xs text-[#a9b9c0] break-all">{source.url}</p><p className="mt-1 text-xs text-[#90a2ad]">{source.group_name} · {source.kind} · {sourceHealth(source,"ru").label}{source.error?` · ${source.error}`:""}</p></div></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm"><button className="text-[#b9f1d4] disabled:opacity-50" disabled={saving||Boolean(busy)||!source.enabled} onClick={()=>{void act("collectSource",{id:source.id})}}>Проверить</button><button className="text-[#b9f1d4] disabled:opacity-50" disabled={saving||Boolean(busy)} onClick={()=>startEdit(source)}>Изменить</button><button className="text-[#b9f1d4] disabled:opacity-50" disabled={saving||Boolean(busy)} onClick={()=>{void manage("sourceToggle",{id:source.id,enabled:!source.enabled})}}>{source.enabled?"Приостановить":"Возобновить"}</button><button className="text-[#ffaaa0] disabled:opacity-50" disabled={saving||Boolean(busy)} onClick={()=>{setError("");setRemoving(source)}}>Удалить</button></div></div>)}</div>
  <Dialog open={open} onOpenChange={setOpen}>
   <DialogContent className="max-h-[90vh] overflow-y-auto bg-[#14202d] border-[#45606b]">
    <DialogHeader><DialogTitle>{draft.id?"Изменить источник":"Добавить источник"}</DialogTitle></DialogHeader>
    <form className="space-y-4" onSubmit={e=>{e.preventDefault();void save()}}>
     <label className="block text-sm">Название<Input className="mt-1" required maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
     <label className="block text-sm">Ссылка HTTPS<Input className="mt-1" type="url" required value={draft.url} placeholder="https://..." onChange={e=>{const url=e.target.value;setDraft({...draft,url,kind:!draft.id?(/^https:\/\/t\.me\//i.test(url)?"telegram":/\.xml(?:\?|$)|\/(?:rss|atom|feed)(?:[/?]|$)/i.test(url)?"rss":"web"):draft.kind})}}/></label>
     <label className="block text-sm">Тип<div className="mt-1 [&>div]:w-full"><NativeSelect className="w-full border-[#45606b] bg-[#0d1420] text-white" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><NativeSelectOption value="web">Сайт</NativeSelectOption><NativeSelectOption value="rss">RSS / Atom</NativeSelectOption><NativeSelectOption value="telegram">Публичный Telegram-канал</NativeSelectOption><NativeSelectOption value="json">JSON CISA KEV</NativeSelectOption></NativeSelect></div></label>
     <label className="block text-sm">Рубрика<div className="mt-1 [&>div]:w-full"><NativeSelect className="w-full border-[#45606b] bg-[#0d1420] text-white" value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}>{groups.map(group=><NativeSelectOption key={group} value={group}>{group}</NativeSelectOption>)}</NativeSelect></div></label>
     <p className="text-xs text-[#a9b9c0]">Новый источник попадёт в мониторинг сразу. После проверки доступные материалы пройдут разбор.</p>
     {error&&<p role="alert" className="text-sm text-[#ffaaa0]">{error}</p>}
     <Button type="submit" disabled={saving}>{saving?"Сохраняем…":"Сохранить источник"}</Button>
    </form>
   </DialogContent>
  </Dialog>
  <AlertDialog open={Boolean(removing)} onOpenChange={value=>{if(!value)setRemoving(null)}}><AlertDialogContent className="bg-[#14202d] border-[#45606b] text-[#ecf3f4]"><AlertDialogHeader><AlertDialogTitle>Удалить «{removing?.name}»?</AlertDialogTitle><AlertDialogDescription className="text-[#a9b9c0]">Площадка исчезнет из мониторинга. Уже опубликованные материалы останутся в ленте со ссылками на первоисточники.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>Отмена</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={()=>{if(removing)void manage("sourceRemove",{id:removing.id}).then(ok=>{if(ok)setRemoving(null)})}}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
const weekdays=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
function CollectionSchedulePanel({schedule,run,busy,act}:{schedule?:CollectionSchedule;run?:CollectionRun|null;busy:string;act:(name:string,payload?:Record<string,unknown>)=>Promise<unknown>}){
 const [mode,setMode]=useState<"daily"|"selected">(schedule?.mode||"daily");
 const [days,setDays]=useState<number[]>(schedule?.days||[1,2,3,4,5,6,7]);
 const [time,setTime]=useState(schedule?.time_msk||"05:00");
 useEffect(()=>{if(schedule){setMode(schedule.mode);setDays(schedule.days);setTime(schedule.time_msk)}},[schedule?.updated_at]);
 const toggle=(day:number)=>setDays(current=>current.includes(day)?current.filter(d=>d!==day):[...current,day].sort());
 return <div className="panel mt-5"><h2 className="text-xl font-semibold">Автоматический сбор новостей</h2><p className="hint">Сервер проверяет включённые источники и публикует новые карточки без участия читателей. Время указано по Москве.</p>
  <div className="mt-5 flex flex-wrap gap-2"><Button variant={mode==="daily"?"default":"secondary"} aria-pressed={mode==="daily"} onClick={()=>setMode("daily")}>Ежедневно</Button><Button variant={mode==="selected"?"default":"secondary"} aria-pressed={mode==="selected"} onClick={()=>setMode("selected")}>По дням недели</Button></div>
  {mode==="selected"&&<fieldset className="mt-5"><legend className="mb-2 text-sm">Дни запуска</legend><div className="flex flex-wrap gap-2">{weekdays.map((name,index)=><button type="button" key={name} aria-pressed={days.includes(index+1)} onClick={()=>toggle(index+1)} className={`min-w-11 rounded-lg border px-3 py-2 text-sm ${days.includes(index+1)?"border-[#b9f1d4] bg-[#254338] text-[#b9f1d4]":"border-[#45606b] text-[#a9b9c0]"}`}>{name}</button>)}</div></fieldset>}
  <label className="mt-5 block max-w-48 text-sm">Время (МСК)<Input className="mt-2" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>
  <Button className="mt-5" disabled={Boolean(busy)||mode==="selected"&&!days.length||!time} onClick={()=>{void act("collectionSchedule",{mode,days,time})}}>{busy==="collectionSchedule"?"Сохраняем…":"Сохранить расписание"}</Button>
  <p className="mt-3 text-xs text-[#90a2ad]">Если сервер пропустит время запуска, он выполнит сбор после восстановления в тот же день. Повторного сбора за уже обработанный день не будет.</p>
  {run&&<div className="mt-5 border-t border-[#344655] pt-4 text-sm"><span className="text-[#b9f1d4]">Последний запуск · {run.slot}</span><p className="mt-1 text-[#a9b9c0]">{run.status==="running"?"Выполняется":run.status==="partial"?"Завершён с ошибками":"Завершён"} · проверено {run.checked} из {run.total} · новых карточек {run.added}{run.errors?` · ошибок ${run.errors}`:""}</p></div>}
 </div>;
}
function AdminPanel({data,busy,act,reload,onEdit}:{data:State;busy:string;act:(name:string,payload?:Record<string,unknown>)=>Promise<unknown>;reload:()=>Promise<void>;onEdit:(s:Story)=>void}){
 const [file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[weekDraft,setWeekDraft]=useState<Week|null>(null);
 const drafts=(data.stories||[]).filter(s=>s.state!=="published");
 const [adminDrafts,setAdminDrafts]=useState<Story[]>(drafts);
 // Read unpublished cards via admin endpoint; state API deliberately excludes them from public feeds.
 useEffect(()=>{void fetch("/api/admin-drafts").then(r=>r.json()).then(v=>{const data=v as {stories?:Story[]};if(Array.isArray(data.stories))setAdminDrafts(data.stories)}).catch(()=>{})},[data.uploads?.length]);
 const upload=async()=>{if(!file)return;setUploading(true);setError("");try{const form=new FormData();form.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:form});const result=await r.json() as {error?:string;outcomes?:Array<{source:string}>};if(!r.ok)throw new Error(result.error);setFile(null);await reload()}catch(e){setError(e instanceof Error?e.message:"Ошибка загрузки")}finally{setUploading(false)}};
 return <section><Eyebrow>Управление</Eyebrow><h1 className="page-title">Редактор</h1><p className="mt-3 text-[#a9b9c0]">Контроль источников, демонстрационных файлов и обзора недели.</p>
  <div className="mt-8 grid md:grid-cols-3 gap-3">{([ ["OpenAI API",data.setup?.openai],["Telegram Login",data.setup?.telegram],["Бот",data.setup?.bot] ] as const).map(([name,ready])=><div key={name} className="panel !p-4"><span className="text-sm text-[#9bacb5]">{name}</span><div className={`mt-2 font-semibold ${ready?"text-[#b9f1d4]":"text-[#e0c095]"}`}>{ready?"Готов":"Не подключён"}</div></div>)}</div>
  <CollectionSchedulePanel schedule={data.collectionSchedule} run={data.collectionRun} busy={busy} act={act}/>
  <div className="grid lg:grid-cols-2 gap-5 mt-8"><SourceManager sources={data.sources||[]} busy={busy} act={act} reload={reload}/>
   <div className="panel"><h2 className="text-xl font-semibold">Демонстрационный файл</h2><p className="hint">PDF, DOCX, PPTX или Markdown. Только вымышленные сведения, до 8 МБ.</p><label className="mt-5 flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#648077] text-sm text-[#b9f1d4] hover:bg-[#1d2e3c]"><FileUp size={21} className="mb-2"/>{file?.name||"Выбрать файл"}<input type="file" accept=".pdf,.docx,.pptx,.md,.markdown" className="sr-only" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button disabled={!file||uploading} className="mt-4" onClick={()=>{void upload()}}>{uploading?"Обрабатываем…":"Загрузить и разобрать"}</Button>{error&&<p role="alert" className="text-[#ffaaa0] mt-3 text-sm">{error}</p>}<div className="mt-4 text-sm text-[#a9b9c0]">{(data.uploads||[]).map(f=><div key={f.id} className="mt-2">{f.filename} · {f.status}{f.error&&<span className="text-[#ffaaa0]"> · {f.error}</span>}</div>)}</div></div>
  </div>
  <div className="panel mt-5"><h2 className="text-xl font-semibold">Карточки на проверке</h2>{adminDrafts.length?adminDrafts.map(s=><div className="flex justify-between gap-3 border-t border-[#344655] py-3 mt-3" key={s.id}><span className="text-sm">{s.title_ru||s.title_original}</span><Button size="sm" variant="secondary" onClick={()=>onEdit(s)}>Открыть</Button></div>):<p className="hint">Ожидают загрузки демонстрационного файла.</p>}</div>
  <div className="panel mt-5"><h2 className="text-xl font-semibold">Заявки на источники</h2>{(data.suggestions||[]).filter(s=>s.status==="pending").length?(data.suggestions||[]).filter(s=>s.status==="pending").map(s=><div key={s.id} className="border-t border-[#344655] py-3 mt-3"><p className="break-all text-sm">{s.url}</p><p className="text-xs text-[#a9b9c0] mt-1">{s.proposer||"Читатель"}</p><div className="flex gap-2 mt-2"><Button size="sm" onClick={()=>{void act("reviewSuggestion",{id:s.id,approved:true})}}>Принять</Button><Button size="sm" variant="secondary" onClick={()=>{void act("reviewSuggestion",{id:s.id,approved:false})}}>Отклонить</Button></div></div>):<p className="hint">Новых заявок нет.</p>}</div>
  <div className="panel mt-5"><h2 className="text-xl font-semibold">Картина недели</h2><p className="hint">ИИ создаёт обзор. Редактор может проверить и отправить его читателям.</p><Button className="mt-4" disabled={Boolean(busy)} onClick={()=>{void act("rebuildWeek")}}>Пересобрать обзор на свежих материалах</Button>{(data.weeks||[]).map(w=><div key={w.id} className="mt-5 border-t border-[#344655] pt-4"><p className="text-sm text-[#b9f1d4]">{w.id} · {w.status}</p><h3 className="font-semibold mt-1">{w.title_ru}</h3><p className="text-sm text-[#a9b9c0] mt-2 line-clamp-3">{w.body_ru}</p><div className="flex gap-2 mt-3 flex-wrap">{w.status==="draft"?<Button size="sm" onClick={()=>setWeekDraft(w)}>Проверить и опубликовать</Button>:<><Button size="sm" variant="secondary" onClick={()=>setWeekDraft(w)}>Редактировать</Button><Button size="sm" variant="secondary" onClick={()=>{void act("testDigest",{id:w.id})}}>Тест себе</Button><Button size="sm" onClick={()=>{void act("sendWeek",{id:w.id})}}>Отправить подписчикам</Button></>}</div></div>)}</div>
  <div className="panel mt-5"><h2 className="text-xl font-semibold">Подключение бота и журнал</h2><Button className="mt-4" variant="secondary" onClick={()=>{void act("setupBot")}}>Настроить вебхук бота</Button><div className="mt-5 space-y-2">{(data.jobs||[]).map(j=><div className="border-t border-[#344655] pt-2 text-xs text-[#9bacb5]" key={j.id}>{fmt(j.created_at,"ru")} · {j.type} · {j.status}<p className="mt-1 break-all">{j.detail.slice(0,250)}</p></div>)}</div></div>
  <Dialog open={Boolean(weekDraft)} onOpenChange={v=>{if(!v)setWeekDraft(null)}}><DialogContent className="max-h-[85vh] overflow-y-auto bg-[#14202d] border-[#45606b] sm:max-w-[700px]"><DialogHeader><DialogTitle>Проверка обзора недели</DialogTitle></DialogHeader>{weekDraft&&<div className="space-y-3">{(["title_ru","title_en","body_ru","body_en"] as const).map(k=><label key={k} className="block text-sm">{k}<textarea value={weekDraft[k]} onChange={e=>setWeekDraft({...weekDraft,[k]:e.target.value})} className="w-full mt-1 min-h-24 rounded-lg bg-[#0d1420] border border-[#45606b] p-3"/></label>)}<Button onClick={()=>{void act("publishWeek",{id:weekDraft.id,titleRu:weekDraft.title_ru,titleEn:weekDraft.title_en,bodyRu:weekDraft.body_ru,bodyEn:weekDraft.body_en});setWeekDraft(null)}}>Опубликовать обзор</Button></div>}</DialogContent></Dialog>
 </section>;
}
